import type { NsmpThemeProperties } from '@/utils'
import { compact, fontWeightToNumber, pxToNumber } from './tokenUtils'

export const createGlobalTokens = (theme?: NsmpThemeProperties) => compact({
  colorPrimary: theme?.accentColor,
  colorPrimaryHover: theme?.topMenuButtonHoverBackground,
  colorPrimaryActive: theme?.buttonActiveBackground,
  colorPrimaryBg: theme?.autoInsertValueColor,
  colorPrimaryBgHover: theme?.metaClassHoverBackground,
  colorPrimaryBorder: theme?.autoInsertBorderColor,
  colorPrimaryBorderHover: theme?.accentColor,
  colorPrimaryText: theme?.accentColor,
  colorPrimaryTextHover: theme?.contentHeaderActionLinkHoverColor,
  colorPrimaryTextActive: theme?.workflowSelectedStateColor,

  colorSuccess: theme?.messageActionSuccessColor,
  colorSuccessHover: theme?.messageActionSuccessColor,
  colorSuccessActive: theme?.messageActionSuccessColor,
  colorSuccessBg: theme?.messageActionSuccessBackground,
  colorSuccessBgHover: theme?.messageActionSuccessBackground,
  colorSuccessBorder: theme?.messageActionSuccessColor,
  colorSuccessBorderHover: theme?.messageActionSuccessColor,
  colorSuccessText: theme?.messageActionSuccessColor,
  colorSuccessTextHover: theme?.messageActionSuccessColor,
  colorSuccessTextActive: theme?.messageActionSuccessColor,

  colorWarning: theme?.messageWarningColor,
  colorWarningHover: theme?.messageWarningButtonColor,
  colorWarningActive: theme?.messageWarningButtonColor,
  colorWarningBg: theme?.messageWarningBackground,
  colorWarningBgHover: theme?.systemNotificationBackgroundColorHover,
  colorWarningBorder: theme?.systemNotificationBorderColor,
  colorWarningBorderHover: theme?.pushNotificationBorderColor,
  colorWarningText: theme?.messageWarningButtonColor,
  colorWarningTextHover: theme?.messageWarningButtonColor,
  colorWarningTextActive: theme?.messageWarningButtonColor,

  colorError: theme?.messageErrorColor,
  colorErrorHover: theme?.messageErrorColor,
  colorErrorActive: theme?.messageErrorColor,
  colorErrorBg: theme?.messageErrorBackground,
  colorErrorBgHover: theme?.transitionMatrixErrorCellBackground,
  colorErrorBorder: theme?.messageErrorColor,
  colorErrorBorderHover: theme?.messageErrorColor,
  colorErrorText: theme?.messageErrorColor,
  colorErrorTextHover: theme?.messageErrorColor,
  colorErrorTextActive: theme?.messageErrorColor,

  colorText: theme?.textColor,
  colorTextSecondary: theme?.secondaryTextColor,
  colorTextTertiary: theme?.environmentObjectColor,
  colorTextQuaternary: theme?.disabledTextColor,
  colorTextDisabled: theme?.disabledTextColor,
  colorTextHeading: theme?.blockTitleColor,
  colorTextLabel: theme?.attrTitleColor,
  colorTextDescription: theme?.infoPanelTextColor,
  colorTextLightSolid: theme?.buttonTextColor,
  colorTextPlaceholder: theme?.environmentObjectColor,

  colorBorder: theme?.borderColor,
  colorBorderSecondary: theme?.rowBorderColor,
  colorBorderBg: theme?.rowBorderColorLight,
  colorSplit: theme?.rowBorderColorLight,

  colorBgBase: theme?.baseBackground,
  colorBgContainer: theme?.contentBackground,
  colorBgContainerDisabled: theme?.inputDisabledBackground,
  colorBgLayout: theme?.baseBackground,
  colorBgElevated: theme?.popupFooterBackgroundColor,
  colorBgSpotlight: theme?.popupHeaderBackgroundColor,

  colorFill: theme?.itemSelectedBackground,
  colorFillSecondary: theme?.panelBackground,
  colorFillTertiary: theme?.infoPanelBackground,
  colorFillQuaternary: theme?.rowBorderColorLight,
  colorFillContent: theme?.itemSelectedBackground,
  colorFillContentHover: theme?.defaultHoverBackground,
  colorFillAlter: theme?.panelBackground,

  colorBgTextHover: theme?.defaultHoverBackground,
  colorBgTextActive: theme?.itemSelectedBackground,
  controlOutline: theme?.inputFocusBorderColor,
  controlItemBgActive: theme?.itemSelectedBackground,
  controlItemBgActiveHover: theme?.tableRowSelectedBackground,
  controlItemBgActiveDisabled: theme?.inputDisabledBackground,
  controlHeight: pxToNumber(theme?.inputHeight),
  controlHeightXS: pxToNumber(theme?.buttonHeight),
  controlHeightSM: pxToNumber(theme?.buttonHeight),

  borderRadius: pxToNumber(theme?.inputRadius),
  borderRadiusXS: pxToNumber(theme?.inputRadius),
  borderRadiusSM: pxToNumber(theme?.inputRadius),
  borderRadiusLG: pxToNumber(theme?.inputRadius),
  borderRadiusOuter: pxToNumber(theme?.inputRadius),
  lineWidth: 1,
  lineWidthBold: 2,
  lineType: 'solid',

  fontSize: pxToNumber(theme?.buttonFontSize),
  fontSizeSM: pxToNumber(theme?.buttonFontSize),
  fontFamily: theme?.baseFont,
  fontWeightStrong: fontWeightToNumber(theme?.buttonFontWeight),
  controlPaddingHorizontal: pxToNumber(theme?.inputPaddingLeft),
  controlPaddingHorizontalSM: pxToNumber(theme?.inputPaddingLeft),

  boxShadow: theme?.darkShadow,
  boxShadowSecondary: theme?.lightShadow,
  boxShadowTertiary: theme?.lightShortShadow,
  motionDurationFast: '0.1s',
  motionDurationMid: '0.2s',
  motionDurationSlow: '0.3s',

  colorLink: theme?.linkColor,
  colorLinkHover: theme?.actionLinkHoverColor,
  linkDecoration: 'none',
  linkHoverDecoration: 'none',
  linkFocusDecoration: 'none',
})
